### PR TITLE
(200) Add MAINTAINERS

### PR DESCRIPTION
**Pull request by cprice404**

### CODE REVIEW

**Comment by rlinehan** [comment]
👍

**Review by rlinehan — APPROVED** [review]
(testing, testing... What is this review business?)

Anyway, I approve.

**Comment by cprice404** [comment]
@lindboe @aperiodic this is just a first cut, we can add and remove people from this whenever, but are you two OK with me including you on this repo for now?

**Comment by lindboe** [comment]
yup

**Comment by cprice404** [comment]
@lindboe ty
@aperiodic  ?

**Pull request merged**
